-d C:\Users\32875\Desktop\FPGA\example\digital_measure\impl\gwsynthesis\digital_measure.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\32875\Desktop\FPGA\example\digital_measure\src\digital_measure.cst
-cfg C:\Users\32875\Desktop\FPGA\example\digital_measure\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
